### ISSUE TITLE
What are your top 5 essential node modules...

### ISSUE THREAD

**Issue by paulja** [cmilhench/ama#1]
...and why!

Also, has this list changed over the last few years?

**Comment by cmilhench** [comment]
There are so many to choose from.  Essential either because I use them all the time, I've learnt something wonderful from them, or because they become ubiquitous.  Today I'd go with the following:- [wreck][1], [async][2], [sculpt][3], [grunt][4] and [express][5].

It changes all the time, most recently banishing request in favour of wreck causing the heavens to align and my code to run smoothly again. :-)

[1]: https://www.npmjs.com/package/wreck
[2]: https://www.npmjs.com/package/async
[3]: https://www.npmjs.com/package/sculpt
[4]: https://www.npmjs.com/package/grunt
[5]: https://www.npmjs.com/package/express

**Comment by paulja** [comment]
I've not seen [sculpt](https://www.npmjs.com/package/sculpt) before, can you give an example of where you've used it?

**Comment by cmilhench** [comment]
A while ago I needed to perform some analysis on a document database; taking a feed, doing some transforms\filtering and storing the results in another document database, doing it with streams rather than downloading a large batch was pretty sweet.

Later I even added a CLI so that I could run it ad-hoc.  It looked a little like:
````
curl http://api.source.com/data | my-sculpt-cli | curl http://api.target.com -d @- -XPOST
````
